# Autogenerated by devscripts/update-version.py

__version__ = '2025.04.21.075848'

RELEASE_GIT_HEAD = '5a5632491cb39b36f132f4fc5b73f7472eed4c24'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'jtduan/yt-dlp-nginx'

ORIGIN = 'jtduan/yt-dlp-nginx'

_pkg_version = '2025.04.21.075848'
